services:
  barracuda-thruster-output-server:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    container_name: barracuda-thruster-output-server
    tty: true
    network_mode: host
    dns:
      - 192.168.1.1
    restart: always