services:
  barracuda-thruster-output-controller:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    image: barracuda-thruster-output-controller
    container_name: thruster-controller
    tty: true
    network_mode: host
    restart: "always"
    volumes:
      # - $HOME/.gitconfig:/root/.gitconfig:ro
      - $HOME/.ssh:/root/.ssh
    devices:
      - /dev/i2c-1:/dev/i2c-1
      - /dev/gpiomem:/dev/gpiomem
    environment:
      - ROS_MASTER_URI=http://192.168.2.1:11311
      - ROS_HOSTNAME=192.168.2.148
      - ROS_DISTRO=noetic
    privileged: true
    extra_hosts:
      - "barracuda-orin:192.168.2.1"
