services:
  barracuda-thruster-ouput-server:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    container_name: barracuda-thruster-ouput-server
    tty: true
    network_mode: host
    restart: always
    privileged: true